apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" ## the volume is at /mnt/data on the cluster's node