name: Push Docker image
env:
  CG_REPO: 'https://bmaluff_23@bitbucket.org/devsu/demo-devops-python.git'
  THIRD_PARTY_REPO_URL: ${{ github.event.inputs.remote_repo_url }}
  DOCKERHUB_USERNAME: ${{ github.event.inputs.docker_user }}
  DOCKERHUB_TOKEN: ${{ github.event.inputs.docker_token }}

on:
  workflow_dispatch:
    inputs:
      remote_repo_url:
        description: 'Third-party Docker Registry URL'
        required: true
      docker_user:
        description: 'Docker Username'
        required: true
      docker_token:
        description: 'Docker Password'
        required: true

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out third-party repository
        run: |
          git clone ${{ env.CG_REPO }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: "Dockerfile_production"
          tags: ${{ env.THIRD_PARTY_REPO_URL }}