name: Unit Test 

on:
  workflow_dispatch:
    
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out own repo
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          docker build -t unittest-py -f Dockerfile_test .
          docker run -t unittest-py:latest > unittest.txt

      - name: Upload Docker image artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Docker Image
          path: unittest.txt